#DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT(
	NAME VARCHAR(255) NOT NULL,
	SEX VARCHAR(10),
	STU_NO VARCHAR(255) NOT NULL,
	COLLEGE VARCHAR(255) NOT NULL,
	MAJOR VARCHAR(255) NOT NULL, 
	AD_YEAR VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL, 
	ID VARCHAR(255) NOT NULL,
	PRIMARY KEY (STU_NO)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#DROP TABLE IF EXISTS LOG_INFORMATION;
CREATE TABLE LOG_INFORMATION(
	STU_NO VARCHAR(255),
	LOG_TIME DATETIME,
	IP_ADDRESS VARCHAR(255),
	STATUS VARCHAR(255),
	PRIMARY KEY (STU_NO,LOG_TIME,IP_ADDRESS),
	FOREIGN KEY (STU_NO) REFERENCES STUDENT(STU_NO)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
 
#DROP TABLE IF EXISTS ADMINISTRATOR;#管理员
CREATE TABLE ADMINISTRATOR(
	STU_NO VARCHAR(255) NOT NULL,
	PRIMARY KEY (STU_NO),
	FOREIGN KEY (STU_NO) REFERENCES STUDENT(STU_NO)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
 
#DROP TABLE IF EXISTS EDUCATION_PLAN;
CREATE TABLE EDUCATION_PLAN(
	AD_YEAR VARCHAR(255) NOT NULL,#年级
	MAJOR VARCHAR(255) NOT NULL,#专业
	CLASSIFICATION VARCHAR(255),#是否必修
	CO_NO VARCHAR(255) NOT NULL,#课程号
	CO_100 VARCHAR(255) NOT NULL,#用于获得已选课程的课程号
	CO_NAME VARCHAR(255) NOT NULL,#学生名
	TEACHER VARCHAR(255) NOT NULL,#老师
	CREDITS DECIMAL(3,1),
	TOTAL_HR INT(10),#总课时
	START_TIME DATE,
	END_TIME DATE,
	CLASS_TIME VARCHAR(255),
	MAX_STUDENTS INT(10),
	CO_HR INT(10),#授课课时
	ONLINE_HR INT(10),
	EXPR_HR INT(10),
	PRAC_HR INT(10),
	PRAC_WK INT(10),
	START_SEMENMTER INT(2) NOT NULL,
	IS_MUST INT(2) DEFAULT '0',
	COLLEGE VARCHAR(255) NOT NULL,
	NOTE TEXT,
	PRIMARY KEY (CO_NO)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
 
#DROP TABLE IF EXISTS CHOOSE;/*选过且结课的课*/
CREATE TABLE CHOOSE(
	AD_YEAR VARCHAR(255) NOT NULL,#年级
	MAJOR VARCHAR(255) NOT NULL,#专业
	STU_NO VARCHAR(255) NOT NULL,
	CO_NO VARCHAR(255) NOT NULL,
	GRADE DECIMAL(5,1),
	COMMENT VARCHAR(255),
	PRIMARY KEY (STU_NO,CO_NO),
	FOREIGN KEY (STU_NO) REFERENCES STUDENT(STU_NO),
	FOREIGN KEY (CO_NO) REFERENCES EDUCATION_PLAN(CO_NO)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

#DROP TABLE IF EXISTS EDU_STU_PLAN;/*每个人的学分信息*/
CREATE TABLE EDU_STU_PLAN(
	AD_YEAR VARCHAR(255) NOT NULL,/*入学年份*/
	STU_NO VARCHAR(255) NOT NULL,
	DIRECTION VARCHAR(255),
	FINISHED_CO VARCHAR(255),
	HAS_CREDITS DECIMAL(10,2),
	NOT_CREDITS DECIMAL(10,2),
	PRIMARY KEY (STU_NO),
	FOREIGN KEY (STU_NO) REFERENCES STUDENT(STU_NO)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE NEWS(
	TOPIC VARCHAR(255) NOT NULL,
	COMMENTS VARCHAR(255) NOT NULL,
	COMMENTER VARCHAR(255) NOT NULL,
	CREATE_TIME timestamp NOT NULL DEFAULT NOW(),
	NEWS_ID VARCHAR(255) NOT NULL,
	IS_FIRST VARCHAR(255) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE announcement (
    id INT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    time_str DATETIME NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE announcement_visibility (
    id INT AUTO_INCREMENT PRIMARY KEY,
    announcement_id INT NOT NULL,
    target_type ENUM('student', 'college', 'major') NOT NULL,
    target_id VARCHAR(255) NOT NULL,
    FOREIGN KEY (announcement_id) REFERENCES announcement(id)
        ON DELETE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

